### ISSUE TITLE
Add licensing / license file

### ISSUE THREAD

**Issue by norro** [ros-safety/software_watchdogs#4]
I suggest Apache Public License 2.0, same as the other repos in ros-safety.

**Comment by norro** [comment]
@robbel, @gbiggs  Does APL sound reasonable to you (since you are the only contributors, yet)?

**Comment by gbiggs** [comment]
The package is already licensed under Apache 2.0, so that would be the appropriate license file to add.

**Comment by robbel** [comment]
APL sounds good, I'll add the license to the repository (#5)
